### PR TITLE
List of 5000 packages across package types

### PR DESCRIPTION
**Pull request by majurg**
* Top 1000 Maven package Download URLs collected
* Top 1000 PyPI package Download URLs collected
* Top 1000 NuGet package Download URLs collected
* Top 1000 NPM package Download URLs collected
* Top 1000 RubyGem package Download URLs collected

Addresses: #3

Signed-off-by: Steven Esser <sesser@nexb.com>

### CODE REVIEW

**Comment by pombredanne** [comment]
Thanks! this is looking great :+1: 
Let me review and merge.
As a follow up, how things look like when you run on ~50 packages, like 10 for each type?
Also we might want to add the ClearlyDefined coordinates for each package.

**Comment by majurg** [comment]
@pombredanne Take a look now; I have added the results from a 50+ package scoring run.

Additionally, I have added a new column: `provider` as additional clearlydefiend coordinate data.

**Comment by majurg** [comment]
I was a bit unsure of provider values for generic packages (like `zlib`). 

In this case I just listed `web` as the provider as the zlib package listed in the csv file is found on their own website and not on a "popular" package repository.

**Comment by pombredanne** [comment]
> I was a bit unsure of provider values for generic packages (like zlib).

I am not sure that these bare, generic URLs can be handled by CD at this time yet.
This is looking great and I am merging now.

**Pull request merged**
